[package]
name = "splitter"
version = "0.1.0"
authors = ["steven.liatti <steven.liatti@hesge.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
